# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP_NAME: "rg-vnet-two-subnets"
      LOCATION: "westeurope"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repo
        uses: actions/checkout@v2
        
      - name: Substitute default parameters
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{github.workspace}}/Samples/Network/vnet-two-subnets/azpester/definition.parameters.json'
        env:
          parameters.subscriptionId.value: ${{secrets.SUBSCRIPTION_ID}}
          parameters.resourceGroupName.value: ${{env.RESOURCE_GROUP_NAME}}
          parameters.location.value: ${{env.LOCATION}}
      
      - name: Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
          
      - name: Install AzPester
        uses: azure/powershell@v1
        with:
          azPSVersion: '5.8.0'
          inlineScript: |
            Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
            Find-Module -Name Az | Install-Module -Scope CurrentUser
            Find-Module -Name Pester | Install-Module -Scope CurrentUser 
            Import-Module "${{github.workspace}}\Source\AzPester.psm1"
            
      - name: Deploy rg-vnet-two-subnets
        uses: azure/powershell@v1
        with:
          azPSVersion: '5.8.0'
          inlineScript: |      
            New-AzResourceGroup -Name ${{env.RESOURCE_GROUP_NAME}} -Location ${{env.LOCATION}}
            New-AzResourceGroupDeployment -ResourceGroupName ${{env.RESOURCE_GROUP_NAME}} -TemplateFile "${{github.workspace}}\Samples\Network\vnet-two-subnets\arm\azuredeploy.json"
          
      - name: Test rg-vnet-two-subnets
        uses: azure/powershell@v1
        with:
          azPSVersion: '5.8.0'
          inlineScript: |      
            cd "${{github.workspace}}\Samples\Network\vnet-two-subnets\azpester"
            Invoke-AzPester -Definition definition.json -Parameters definition.parameters.json
            

